# Generated by Django 5.1.4 on 2024-12-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=255)),
                ('contactno', models.IntegerField(null=True)),
                ('emailid', models.CharField(max_length=255)),
                ('DoctorName', models.CharField(max_length=255)),
                ('Date', models.DateField(null=True)),
                ('Time', models.TimeField(null=True)),
                ('fee', models.IntegerField(null=True)),
            ],
        ),
    ]
