# Generated by Django 5.1.4 on 2024-12-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=255)),
                ('hrName', models.CharField(max_length=255)),
                ('openingdate', models.DateField(null=True)),
                ('closeddate', models.DateField(null=True)),
                ('notes', models.CharField(max_length=500)),
                ('status', models.IntegerField(null=True)),
                ('deparment', models.CharField(max_length=500)),
                ('baseSalary', models.IntegerField(null=True)),
            ],
        ),
    ]
