# Generated by Django 5.1.4 on 2024-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='hiringManager',
            field=models.CharField(default='Ankit', max_length=255),
            preserve_default=False,
        ),
    ]
