# Generated by Django 5.1.4 on 2024-12-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=255)),
                ('specialisation', models.CharField(max_length=255)),
                ('contact', models.IntegerField(null=True)),
                ('emailId', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=255)),
                ('achievement', models.CharField(max_length=255)),
                ('fee', models.IntegerField(null=True)),
            ],
        ),
    ]
